name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build static assets
        env:
          PUBLIC_URL: https://${{ secrets.DO_SPACE_NAME }}.${{ secrets.DO_SPACE_REGION }}.digitaloceanspaces.com/
          REACT_APP_GOOGLE_MEASUREMENT_ID: ${{ secrets.REACT_APP_GOOGLE_MEASUREMENT_ID }}
        run: |
          npm install
          npm run build

      - name: Rsync deployment
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude=".env" --exclude="server/data/" --exclude="public/cryptocurrencies/logo"
          path: "."
          remote_path: /var/www/www.nanolooker.com
          remote_host: ${{ secrets.DO_HOST }}
          remote_user: ${{ secrets.DO_USERNAME }}
          remote_key: ${{ secrets.DO_SSHKEY }}

      - name: Upload to spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: dist
